// AUTO-GENERATED — 请勿手改。生成: python3 scripts/sync_endpoint_catalog.py
// 数据源: bovin/rpc/api_server/*.py；可选 --openapi-url 从运行实例补全英文摘要。
export const endpointCatalog = [
  ["状态", "GET", "/health", "Bot 主循环健康（如 last_process）", "Bot loop health"],
  ["状态", "GET", "/ping", "服务可用性探测", "Service readiness probe"],
  ["状态", "HEAD", "/ping", "服务可用性探测（HEAD）", "Service readiness probe (HEAD)"],
  ["状态", "GET", "/sysinfo", "主机 CPU/内存等负载", "Host CPU/RAM load"],
  ["认证", "POST", "/token/login", "JWT 登录，返回 access/refresh", "JWT login; access + refresh tokens"],
  ["认证", "POST", "/token/refresh", "用 refresh token 换新 access", "Refresh access token"],
  ["信息", "GET", "/logs", "最近日志", "Recent log lines"],
  ["信息", "GET", "/show_config", "运行配置摘要（不含密钥）", "Running config summary (no secrets)"],
  ["信息", "GET", "/version", "程序版本", "Application version"],
  ["运行控制", "POST", "/pause", "暂停新开仓", "Pause new entries"],
  ["运行控制", "POST", "/reload_config", "热重载配置文件", "Reload configuration"],
  ["运行控制", "POST", "/start", "启动交易器", "Start trader"],
  ["运行控制", "POST", "/stop", "停止交易器", "Stop trader"],
  ["运行控制", "POST", "/stopbuy", "停止买入（兼容别名，同 stopentry）", "Stop buying (alias; same as stopentry)"],
  ["运行控制", "POST", "/stopentry", "停止新开仓", "Stop new entries"],
  ["交易与资金", "GET", "/balance", "账户各币种余额", "Balances per currency"],
  ["交易与资金", "GET", "/count", "持仓槽位已用/可用数量", "Open slots used / available"],
  ["交易与资金", "GET", "/daily", "按日盈亏（timescale）", "Daily P/L (timescale)"],
  ["交易与资金", "GET", "/entries", "按入场 tag 统计（可选 pair）", "Stats by enter tag (optional pair)"],
  ["交易与资金", "GET", "/exits", "按出场原因统计", "Stats by exit reason"],
  ["交易与资金", "POST", "/forcebuy", "强制开仓（已弃用，请用 /forceenter）", "Force enter (deprecated; use /forceenter)"],
  ["交易与资金", "POST", "/forceenter", "强制开仓", "Force enter"],
  ["交易与资金", "POST", "/forceexit", "强制平仓", "Force exit"],
  ["交易与资金", "POST", "/forcesell", "强制平仓（已弃用，请用 /forceexit）", "Force exit (deprecated; use /forceexit)"],
  ["交易与资金", "GET", "/mix_tags", "入场 tag × 出场原因组合统计", "Enter tag × exit reason combinations"],
  ["交易与资金", "GET", "/monthly", "按月盈亏", "Monthly P/L"],
  ["交易与资金", "GET", "/performance", "按交易对汇总已完成表现", "Performance grouped by pair"],
  ["交易与资金", "GET", "/profit", "已平仓盈亏汇总", "Closed-trade profit summary"],
  ["交易与资金", "GET", "/profit_all", "扩展利润指标", "Extended profit metrics"],
  ["交易与资金", "GET", "/stats", "盈亏原因与持仓时间等统计", "P/L reasons and holding-time stats"],
  ["交易与资金", "GET", "/status", "当前未平仓列表", "Open positions"],
  ["交易与资金", "GET", "/trade/{tradeid}", "单笔交易详情", "Single trade details"],
  ["交易与资金", "GET", "/trades", "历史已平仓（单次有上限）", "Closed trades (capped per request)"],
  ["交易与资金", "GET", "/trades/open/custom-data", "未平仓 custom-data 列表", "Custom data for open trades"],
  ["交易与资金", "GET", "/trades/{trade_id}/custom-data", "指定仓 custom-data", "Custom data for one trade"],
  ["交易与资金", "DELETE", "/trades/{tradeid}", "从库删除交易记录（需人工处理交易所）", "Delete trade from DB"],
  ["交易与资金", "DELETE", "/trades/{tradeid}/open-order", "取消该笔关联挂单", "Cancel open order for trade"],
  ["交易与资金", "POST", "/trades/{tradeid}/reload", "从交易所重载该笔（实盘）", "Reload trade from exchange (live)"],
  ["交易与资金", "GET", "/weekly", "按周盈亏", "Weekly P/L"],
  ["名单与锁", "GET", "/blacklist", "当前黑名单", "Blacklist"],
  ["名单与锁", "POST", "/blacklist", "加入黑名单", "Add to blacklist"],
  ["名单与锁", "DELETE", "/blacklist", "从黑名单移除若干交易对", "Remove pairs from blacklist"],
  ["名单与锁", "GET", "/locks", "当前锁仓列表", "Pair locks"],
  ["名单与锁", "POST", "/locks", "锁定交易对至指定时间", "Lock pair until datetime"],
  ["名单与锁", "POST", "/locks/delete", "批量删除锁", "Delete locks in batch"],
  ["名单与锁", "DELETE", "/locks/{lockid}", "按 id 删除锁", "Delete lock by id"],
  ["名单与锁", "GET", "/whitelist", "当前白名单", "Whitelist"],
  ["行情与图表", "GET", "/markets", "交易所市场列表（可按 base/quote 过滤）", "Exchange markets (optional filters)"],
  ["行情与图表", "GET", "/pair_candles", "运行中 K 线（交易模式）", "Live candles while bot runs"],
  ["行情与图表", "POST", "/pair_candles", "运行中 K 线，可指定返回列", "Live candles with column filter"],
  ["行情与图表", "GET", "/pair_history", "历史区间 + 策略分析后的 DataFrame（webserver）", "Analyzed history DataFrame (webserver)"],
  ["行情与图表", "POST", "/pair_history", "同上，POST 指定列", "Same with column filter via POST"],
  ["行情与图表", "GET", "/plot_config", "策略图表/指标配置", "Strategy plot config"],
  ["策略与数据", "GET", "/available_pairs", "本地已有 OHLCV 的交易对", "Pairs with local OHLCV data"],
  ["策略与数据", "GET", "/exchanges", "支持的交易所标识列表", "Supported exchange ids"],
  ["策略与数据", "GET", "/freqaimodels", "Bovin AI 模型类名列表", "Bovin AI model class names"],
  ["策略与数据", "GET", "/hyperoptloss", "Hyperopt 损失函数列表与说明", "Hyperopt loss functions"],
  ["策略与数据", "GET", "/strategies", "策略目录下类名列表（webserver）", "Strategy class names (webserver)"],
  ["策略与数据", "GET", "/strategy/{strategy}", "按类名读取策略源码与参数", "Strategy source and parameters by class name"],
  ["回测", "GET", "/backtest", "查询回测状态/结果", "Backtest status or result"],
  ["回测", "POST", "/backtest", "启动回测", "Start backtest"],
  ["回测", "DELETE", "/backtest", "清理回测状态", "Clear backtest state"],
  ["回测", "GET", "/backtest/abort", "中止回测", "Abort backtest"],
  ["回测", "GET", "/backtest/history", "回测历史文件列表", "Backtest history list"],
  ["回测", "GET", "/backtest/history/result", "读取当前/指定历史结果", "Load history result"],
  ["回测", "PATCH", "/backtest/history/{file}", "修补历史条目元数据", "Patch history metadata"],
  ["回测", "DELETE", "/backtest/history/{file}", "删除历史结果文件", "Delete history entry"],
  ["回测", "GET", "/backtest/history/{file}/market_change", "相对买入点的市场涨跌", "Market change vs entry"],
  ["任务与下载", "GET", "/background", "后台任务列表", "Background jobs list"],
  ["任务与下载", "GET", "/background/{jobid}", "单个后台任务状态", "Single job status"],
  ["任务与下载", "POST", "/download_data", "触发下载 K 线等异步任务", "Start data download job"],
  ["Pairlist", "GET", "/pairlists/available", "可用 pairlist 处理器", "Available pairlist handlers"],
  ["Pairlist", "POST", "/pairlists/evaluate", "异步评估白名单", "Evaluate whitelist (async)"],
  ["Pairlist", "GET", "/pairlists/evaluate/{jobid}", "查询 pairlist 评估作业", "Pairlist evaluate job status"],
  ["面板", "GET", "/panel/ai_overview", "AI/策略规则摘要（不含密钥）", "AI / rules overview (no secrets)"],
  ["面板", "POST", "/panel/auth/login", "面板账号登录与菜单权限", "Panel user login + menu ACL"],
  ["面板", "GET", "/panel/binance_board", "转发币安 24h 行情条（面板行情带）", "Binance 24h ticker strip for panel"],
  ["面板", "GET", "/panel/binance_klines", "转发币安现货 K 线（面板图表，免浏览器 CORS）", "Binance spot klines proxy for panel"],
  ["面板", "GET", "/panel/bybit_klines", "转发 Bybit K 线（面板图表）", "Bybit klines proxy for panel"],
  ["面板", "GET", "/panel/coinbase_klines", "转发 Coinbase K 线（面板图表）", "Coinbase candles proxy for panel"],
  ["面板", "GET", "/panel/kucoin_klines", "转发 KuCoin K 线（面板图表）", "KuCoin candles proxy for panel"],
  ["面板", "POST", "/panel/exchange_probe", "服务端用 ccxt 校验交易所 REST 密钥", "Server-side ccxt exchange credential probe"],
  ["面板", "POST", "/panel/llm_probe", "服务端探测 OpenAI 兼容 LLM（DeepSeek 等，免浏览器 CORS）", "Server-side OpenAI-compatible LLM probe (DeepSeek, etc.)"],
  ["面板", "GET", "/panel/okx_klines", "转发 OKX K 线（面板图表）", "OKX candles proxy for panel"],
  ["面板", "GET", "/panel/preferences", "读面板偏好（panel_store.sqlite）", "Read panel preferences"],
  ["面板", "POST", "/panel/preferences", "写面板偏好", "Write panel preferences"],
  ["面板", "GET", "/panel/strategies", "扫描 user_data/strategies", "Scan user_data/strategies"],
  ["面板", "GET", "/panel/strategy-presets", "策略预设（SQLite 种子等）", "Strategy presets (seeded in SQLite)"],
  ["面板", "POST", "/panel/strategy-rules/append", "追加规则片段到 strategy_rules_output", "Append rule snippet to output file"],
  ["面板", "GET", "/panel/ticker", "交易所 24h 行情（ccxt，对齐 headline）", "24h ticker via ccxt"],
  ["面板", "GET", "/panel/users", "列表面板用户", "List panel users"],
  ["面板", "POST", "/panel/users", "新建面板用户", "Create panel user"],
  ["面板", "PATCH", "/panel/users/{user_id}", "更新面板用户/权限", "Update panel user"],
  ["面板", "DELETE", "/panel/users/{user_id}", "删除面板用户", "Delete panel user"],
  ["实时通道", "WEBSOCKET", "/message/ws", "RPC 消息流（token 或 JWT）", "RPC message stream (ws_token or JWT)"],
];
